# Travis-CI setup follow:
# https://slashgear.github.io/how-to-deploy-on-github-pages-with-travis-ci/
# https://www.freecodecamp.org/news/learn-how-to-automate-deployment-on-github-pages-with-travis-ci/
language: generic

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

install:
  # Following suggestion from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -f environment.yml
  - conda activate gammasim-tools-dev

script:
  - make -C docs/ html
  - touch docs/build/html/.nojekyll

# See - https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  verbose: true
  token: $GITHUB_TOKEN
  local_dir: ./docs/build/html/
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master
