# Configuration file for simtools
# gammasim-tools requires one configuration file in yaml format.
# This file should be named config.yml and it should be located at
# the local directory. Alternativelly one can use the funtion
# config.setConfigFileName to set an alternative file. 

# Flag to turn on MongoDB. If False, the older yaml files will be used to access the Model Parameters.
useMongoDB: True
# Path to the MongoDB config file, which will be ignored if useMongoDB is False.
mongoDBConfigFile: ./dbDetails.yml

# List with the locations of the model files. The location of the dataFromTheInstruments is
# required for most of the applications and can be found  in
# https://gitlab.cta-observatory.org/cta-consortium/aswg/simulations/simulation-model/verification/data-from-instrument-teams.
# The location of the directory with the yaml files for the model parameters and the sim_telarray
# config files are required in case useMongoDB is set to False. They can be found 
# https://gitlab.cta-observatory.org/cta-consortium/aswg/simulations/simulation-model/simulation-model-description/-/tree/master/configReports
# and https://gitlab.cta-observatory.org/cta-consortium/aswg/simulations/simulation-model/simulation-model-description/-/tree/master/datFiles.
# The files will always be searched recursively within all the subdirectories inside the directory given by the location.
modelFilesLocations: [
  (...)/configReports,
  (...)/datFiles,
  (...)/dataFromInstrumentTeams
]

# Path to the root directory where the output directory will be created.
outputLocation: .

# Path to the directory containing the data. These data is provided at gammasim-tools/data/.
dataLocation: './data/'

# Path to the root sim_telarray directory, containing the sim_telarray software unpacked and compiled.
simtelPath: None

# Command used to submit jobs to a batch system.
# Use log_out and log_err keywords for std out and std err  
submissionCommand: 'qsub -o log_out -e log_err '
# List of xtra commands to be added in the run scripts for submmission.
# Ex. extraCommands = ['export PATH=/afs/ifh.de/group/cta/cta/software/zstd/:${PATH}']
extraCommands: []


