# configuration file for simtools

databaseLocation: /home/prado/Work/Projects/CTA_MC/gammasim-db

modelFilesLocations: [
  /Users/ogueta/work/cta/Simulations/SimulationModel/ModelDescription/trunk/configReports,
  /Users/ogueta/work/cta/Simulations/SimulationModel/ModelDescription/trunk/datFiles,
  /Users/ogueta/work/cta/Simulations/SimulationModel/Verification/dataFromInstrumentTeams
]

outputLocation: .

simtelPath: /afs/ifh.de/group/cta/scratch/prado/corsika_simtelarray/corsika6.9_simtelarray_20-04-02_VTS-Hadrons

submissionCommand: 'qsub '
