# configuration file for simtools

yamlDBPath: /home/prado/Work/Projects/CTA_MC/svn/Simulations/SimulationModel/ModelDescription/trunk/configReports

databaseLocation: /home/prado/Work/Projects/CTA_MC/gammasim-db

outputLocation: .

simtelPath: /afs/ifh.de/group/cta/scratch/prado/corsika_simtelarray/corsika6.9_simtelarray_20-04-02_VTS-Hadrons

submissionCommand: 'qsub '
