# configuration file for simtools

databaseLocation: /home/prado/Work/Projects/CTA_MC/gammasim-db

modelFilesLocations: [
  /home/prado/Work/Projects/CTA_MC/svn/Simulations/SimulationModel/ModelDescription/trunk/configReports,
  /home/prado/Work/Projects/CTA_MC/svn/Simulations/SimulationModel/ModelDescription/trunk/datFiles,
  /home/prado/Work/Projects/CTA_MC/svn/Simulations/SimulationModel/Verification/dataFromInstrumentTeams,
  /Users/ogueta/work/cta/Simulations/SimulationModel/ModelDescription/trunk/configReports,
  /Users/ogueta/work/cta/Simulations/SimulationModel/ModelDescription/trunk/datFiles,
  /Users/ogueta/work/cta/Simulations/SimulationModel/Verification/dataFromInstrumentTeams
]

outputLocation: .

testDataLocation: './data/'

simtelPath: /Users/ogueta/work/cta/gammasim/gammasim-tools/sim_telarray/22_06_20

# Not used yet
submissionCommand: 'qsub '
