[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "simtools"
description = "Tools for the Simulation System of the CTA Observatory"
readme = "README.rst"
license = { file="LICENSE" }
version = "0.4.0"
authors = [
  { name="Orel Gueta", email="orel.gueta@desy.de" },
  { name="Victor Barbosa Martins", email="victor.barbosa.martins@desy.de" },
  { name="Gernot Maier", email="gernot.maier@desy.de" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD-3-Clause",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "astropy",
    "eventio",
    "matplotlib",
    "numpy",
    "pyyaml",
    "pymongo",
    "pyproj",
    "scipy",
    "zstandard",
]

[project.optional-dependencies]
"tests" = [
    "pytest",
    "pytest-cov",
]
"dev" = [
    "pre-commit",
    "pyflakes",
]
"doc" = [
    "numpydoc",
    "sphinx",
    "sphinx_rtd_theme",
]

[project.urls]
"documentation" = "https://gammasim.github.io/gammasim-tools/"
"repository" = "https://github.com/gammasim/gammasim-tools"
"bug tracker" = "https://github.com/gammasim/gammasim-tools/issues"

[project.scripts]
simtools-print-array-elements = "simtools.applications.print_array_elements:main"
[tool.setuptools.packages.find]
