[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "gammasimtools"
description = "Tools for the Simulation System of the CTA Observatory"
readme = "README.rst"
license = { file="LICENSE" }
version = "0.4.0"
authors = [
  { name="Orel Gueta", email="orel.gueta@desy.de" },
  { name="Victor Barbosa Martins", email="victor.barbosa.martins@desy.de" },
  { name="Gernot Maier", email="gernot.maier@desy.de" },
  { name="Raul Prado" },
]
maintainers = [
  { name="Orel Gueta", email="orel.gueta@desy.de" },
  { name="Victor Barbosa Martins", email="victor.barbosa.martins@desy.de" },
  { name="Gernot Maier", email="gernot.maier@desy.de" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD-3-Clause",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "astropy",
    "boost-histogram",
    "eventio",
    "matplotlib",
    "numpy",
    "pyyaml",
    "pymongo",
    "pyproj",
    "scipy",
    "zstandard",
]

[project.optional-dependencies]
"tests" = [
    "pytest",
    "pytest-cov",
]
"dev" = [
    "pre-commit",
    "pyflakes",
]
"doc" = [
    "numpydoc",
    "sphinx",
    "sphinx_rtd_theme",
]

[project.urls]
"documentation" = "https://gammasim.github.io/simtools/"
"repository" = "https://github.com/gammasim/simtools"
"bug tracker" = "https://github.com/gammasim/simtools/issues"

[project.scripts]
simtools-add-file-to-db = "simtools.applications.add_file_to_db:main"
simtools-compare-cumulative-psf = "simtools.applications.compare_cumulative_psf:main"
simtools-derive-mirror-rnda = "simtools.applications.derive_mirror_rnda:main"
simtools-get-file-from-db = "simtools.applications.get_file_from_db:main"
simtools-get-parameter = "simtools.applications.get_parameter:main"
simtools-make-regular-arrays = "simtools.applications.make_regular_arrays:main"
simtools-plot-layout-array = "simtools.applications.plot_layout_array:main"
simtools-plot-simtel-histograms = "simtools.applications.plot_simtel_histograms:main"
simtools-print-array-elements = "simtools.applications.print_array_elements:main"
simtools-produce-array-config = "simtools.applications.produce_array_config:main"
simtools-production = "simtools.applications.production:main"
simtools-sim-showers-for-trigger-rates = "simtools.applications.sim_showers_for_trigger_rates:main"
simtools-simulate-prod = "simtools.applications.simulate_prod:main"
simtools-submit-data-from-external = "simtools.applications.submit_data_from_external:main"
simtools-tune-psf = "simtools.applications.tune_psf:main"
simtools-validate-camera-efficiency = "simtools.applications.validate_camera_efficiency:main"
simtools-validate-camera-fov = "simtools.applications.validate_camera_fov:main"
simtools-validate-optics = "simtools.applications.validate_optics:main"
[tool.setuptools.packages.find]

[tool.setuptools_scm]
write_to = "simtools/_version.py"
