# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: docker-corsika-simtelarray

on:
  workflow_dispatch:
  pull_request:
    paths:
      - './docker/Dockerfile-simtelarray'
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  download:
    runs-on: ubuntu-latest
    steps:
      - name: download corsikasimtelpackage
        run: |
          wget --no-verbose https://syncandshare.desy.de/index.php/s/${{ secrets.CLOUD_SIMTEL_240318 }}/download
          mv download corsika7.7_simtelarray.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: corsika-package
          path: corsika7.7_simtelarray.tar.gz

  prepare:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


  build-corsika-simtelarray:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        type: ['prod6-sc']

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
          images: ${{ env.REGISTRY }}/gammasim/simtools-corsika-sim-telarray-${{ matrix.type }}
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          build-args: '{"BUILD_OPT": ${{ matrix.type }}, "HADRONIC_MODEL": "qgs2"}'
          push:
            ${{ github.event_name == 'release' || github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
          file: ./docker/Dockerfile-simtelarray
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}-corsika-sim-telarray-${{ matrix.type }}
