---
name: CI-docs
# Build and deploy docs to gh-pages

on:
  pull_request:
    branches: [master]
    types: [opened, closed, synchronize]

jobs:

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install conda dependencies
        env:
          PYTHON_VERSION: 3.10.4
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          sed -i -e "s/- python=3.9/- python=$PYTHON_VERSION/g" environment.yml
          conda env create -f environment.yml
          conda activate gammasim-tools-dev
          echo 'source $CONDA/etc/profile.d/conda.sh' >> ~/.bash_profile
          echo 'conda activate gammasim-tools-dev' >> ~/.bash_profile
          echo 'pip install -e .' >> ~/.bash_profile
          python --version

      - name: Build docs
        shell: bash -l {0}
        run: |
          make -C docs/ html
          touch docs/build/html/.nojekyll

      - name: Deploy to gihub pages
        # only run when PR is merged
        if: github.event.pull_request.merged
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
          SINGLE_COMMIT: true
