---
name: CI-integrationtests
# Execute integration tests for applications
#
env:
  SIMTOOLS_SIMTEL_PATH: ${{ github.workspace }}/
  SIMTOOLS_DB_SERVER: ${{ secrets.DB_SERVER }}
  SIMTOOLS_DB_API_USER: ${{ secrets.DB_API_USER }}
  SIMTOOLS_DB_API_PW: ${{ secrets.DB_API_PW }}
  SIMTOOLS_DB_API_PORT: ${{ secrets.DB_API_PORT }}

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  integrationtests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            install-method: mamba
            container:
              image: ghcr.io/gammasim/simtools-corsika_sim_telarray:latest

          - os: ubuntu-latest
            python-version: "3.9"
            install-method: pip
            container:
              image: ghcr.io/gammasim/simtools-corsika_sim_telarray:latest

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install mamba dependencies
        if: matrix.install-method == 'mamba'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: python=${{ matrix.python-version }}
          init-shell: bash

      - name: Python setup
        if: matrix.install-method == 'pip'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Python dependencies
        run: |
          python --version
          pip install '.[tests,dev,doc]'

      - name: check for python
        run: |
          python --version

      - name: Integration tests
        shell: bash -l {0}
        run: pytest --color=yes --durations=10 --no-cov tests/integration_tests/
