---
name: CI-local-db-integrationtests
# Integration tests for applications (using a local database

env:
  SIMTOOLS_DB_SERVER: ${{ secrets.DB_SERVER }}
  SIMTOOLS_DB_API_USER: ${{ secrets.DB_API_USER }}
  SIMTOOLS_DB_API_PW: ${{ secrets.DB_API_PW }}
  SIMTOOLS_DB_API_PORT: ${{ secrets.DB_API_PORT }}
  SIMTOOLS_DB_SIMULATION_MODEL: "CTAO-Simulation-Model-LATEST"
  SIMTOOLS_SIMTEL_PATH: "/workdir/sim_telarray/"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  integrationtests-db:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/gammasim/simtools-dev:latest
      options: --user 0
    strategy:
      fail-fast: false
      matrix:
        type: ['2024-02-01']

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Set PATH
        run: |
          echo "PATH=\$PATH:/usr/bin:/usr/local/bin:$SIMTOOLS_SIMTEL_PATH" >> "$GITHUB_ENV"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-username: api
          mongodb-password: password
          mongodb-db: CTAO-Simulation-Model-v0-3-0
          mongodb-container-name: simtools-mongodb

      - name: Prepare simtools
        shell: bash -l {0}
        run: |
          source /workdir/env/bin/activate
          pip install '.[tests,dev,doc]'
          export PYTHONPATH=$PYTHONPATH:.

      - name: Clone and upload model parameter repository
        run: |
          git clone --depth=1 https://gitlab.cta-observatory.org/cta-science/simulations/simulation-model/model_parameters.git
          cd model_parameters/model_versions
          filename=".env"
          cat << EOF > "$filename"
          SIMTOOLS_DB_API_PORT=27017
          SIMTOOLS_DB_SERVER='simtools-mongodb'
          SIMTOOLS_DB_API_USER='api'
          SIMTOOLS_DB_API_PW='password'
          SIMTOOLS_DB_API_AUTHENTICATION_DATABASE='admin'
          SIMTOOLS_DB_SIMULATION_MODEL='CTAO-Simulation-Model-v0-3-0'
          EOF
          simtools-db-add-model-parameters-from-repository-to-db --input_path "./metadata" --db_name "CTAO-Simulation-Model-v0-3-0" --type "metadata"

      - name: Run integration tests
        shell: bash -l {0}
        run: |
          pytest --model_version=${{ matrix.type }} --color=yes --durations=20 -n auto --dist loadscope --no-cov tests/integration_tests/
