---
name: CI-integrationtests
# Execute integration tests for applications

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  integrationtests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gammasim/simtools-dev:latest
      env:
        SIMTOOLS_SIMTEL_PATH: "/workdir/sim_telarray/"
        SIMTOOLS_DB_SERVER: ${{ secrets.DB_SERVER }}
        SIMTOOLS_DB_API_USER: ${{ secrets.DB_API_USER }}
        SIMTOOLS_DB_API_PW: ${{ secrets.DB_API_PW }}
        SIMTOOLS_DB_API_PORT: ${{ secrets.DB_API_PORT }}

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:

     - name: checkout
       uses: actions/checkout@v4

     - name: Set PATH for bash
       run: |
          echo "PATH=\$PATH:/usr/bin:/usr/local/bin:$SIMTOOLS_SIMTEL_PATH" >> $GITHUB_ENV

     - name: Install Python dependencies
       run: |
          python --version
          source /workdir/env/bin/activate
          pip install '.[tests,dev,doc]'
          pytest -x --color=yes --durations=10 --no-cov tests/integration_tests/
