---
name: CI-integrationtests
# Execute integration tests for applications
#
env:
  SIMTOOLS_SIMTEL_PATH: ${{ github.workspace }}/
  SIMTOOLS_DB_SERVER: ${{ secrets.DB_SERVER }}
  SIMTOOLS_DB_API_USER: ${{ secrets.DB_API_USER }}
  SIMTOOLS_DB_API_PW: ${{ secrets.DB_API_PW }}
  SIMTOOLS_DB_API_PORT: ${{ secrets.DB_API_PORT }}

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  integrationtests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gammasim/simtools-dev:latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup simtools
        run: |
          source /workdir/env/bin/activate
          pip install -e .

      - name: check for python
        run: |
          python --version

      - name: Integration tests
        shell: bash -l {0}
        run: pytest --color=yes --durations=10 --no-cov tests/integration_tests/
