---
name: CI-integrationtests
# Execute integration tests for applications
#

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  integrationtests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gammasim/simtools-corsika_sim_telarray:latest
      options: --user 1001
      env:
        SIMTOOLS_SIMTEL_PATH: "/workdir/sim_telarray/"
        PATH:  "/workdir/sim_telarray/env/bin/:$PATH"
        SIMTOOLS_DB_SERVER: ${{ secrets.DB_SERVER }}
        SIMTOOLS_DB_API_USER: ${{ secrets.DB_API_USER }}
        SIMTOOLS_DB_API_PW: ${{ secrets.DB_API_PW }}
        SIMTOOLS_DB_API_PORT: ${{ secrets.DB_API_PORT }}

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install mamba dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: python=3.9
          init-shell: bash

      - name: Python dependencies
        run: |
          python --version
          pip install '.[tests,dev,doc]'

      - name: Integration tests
        shell: bash -l {0}
        run: pytest -x --color=yes --durations=10 --no-cov tests/integration_tests/
