name: CI-schema-validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'simtools/schemas/model_parameters/*'

jobs:

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Model parameter schema validation
        run: |
          find "simtools/schemas/model_parameters/" -name '*.json' > tmp
          while IFS= read -r file; do
            echo "Testing parameter $file"
            schema_file="./schema/$(basename "$file" .json).schema.yml"
            python simtools/applications/validate_file_using_schema.py \
              --file_name "$file" \
              --schema "$schema_file" \
              --data_type "model_parameter" \
              --log_level DEBUG
          done < tmp
