---
name: CI-sim_telarray

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  sim_telarray:
    name: sim_telarray testing
    runs-on: ubuntu-latest
    steps:
      - name: docker running
        uses: addnab/docker-run-action@v3
        with:
          image: gernotmaier/gammasim-tools-dev:v0.1.1
          options: -v ${{ github.workspace }}:/workdir/external
          run: |
            /workdir/sim_telarray/sim_telarray/sim_telarray
