---
name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install conda dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda install -c conda-forge mamba
          sed -i -e "s/- python<=3.8/- python=$PYTHON_VERSION/g" environment.yml
          mamba env create -f environment.yml
          conda activate gammasim-tools-dev
          echo 'source $CONDA/etc/profile.d/conda.sh' >> ~/.bash_profile
          echo 'conda activate gammasim-tools-dev' >> ~/.bash_profile
          source set_simtools.sh
          python --version

      - name: pyflakes liniting
        shell: bash -leo pipefail {0}
        run: |
          mamba install -q pyflakes
          pyflakes .

      #- name: Tests
      #  shell: bash -leo pipefail {0}
      #  run: |
      #    conda activate gammasim-tools-dev
      #    source set_simtools.sh
      #    pytest


      ### DOCS
      - name: Build docs
        run: |
          make -C docs/ html
          touch docs/build/html/.nojekyll

      - name: Deploy to gihub pages
        # only run on push to master
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/docs' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
          SINGLE_COMMIT: true
